/**
 * @file Memory.kt
 * @brief Defines the data entity for a single memory stored in the Room database.
 *
 * This file contains the `Memory` data class, which represents the schema for the "memories"
 * table in the application's database.
 */
package com.blurr.voice.data

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents a single memory entity to be stored in the Room database.
 *
 * Each instance of this class corresponds to a row in the "memories" table. It holds the
 * user's original text, a vector embedding of that text, and a timestamp.
 *
 * @property id The unique identifier for the memory, auto-generated by the database.
 * @property originalText The raw text content of the memory (e.g., a user's instruction or a piece of information).
 * @property embedding A JSON string representation of the numerical vector embedding for the `originalText`.
 * @property timestamp The time the memory was created, in milliseconds since the epoch.
 */
@Entity(tableName = "memories")
data class Memory(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    val originalText: String,
    val embedding: String, // Stored as JSON string of numbers
    val timestamp: Long = System.currentTimeMillis()
) 